### PR TITLE
Update widget.html

### PR DESCRIPTION
**Pull request by SalahAdDin**
Fix problem with widget offside.

### CODE REVIEW

**Comment by riklaunim** [comment]
this is not the fix I intended it to have. That margin was needed to handle inlined editors in standard django admin.

**Comment by SalahAdDin** [comment]
Well, then which is the fix?

**Comment by riklaunim** [comment]
I want to do it configurable in some way so that it's easy to change the "effect". Quite likely a CSS class that inline widget users would style.

**Comment by SalahAdDin** [comment]
Oh, thank you :)

**Comment by riklaunim** [comment]
fix in https://github.com/shaunsephton/django-ckeditor/pull/128

**Pull request closed without merging**
